---
title: "APM466 A1"
author: "Zhengyu Li"
date: "2/16/2022"
output: html_document
---

```{r Setup, message=FALSE}
# download all the useful pac first
library(NLRoot)
library(janitor)
library(WriteXLS)
library(readxl)
library(tidyverse)
library(SciViews)
library(nleqslv)
library(reshape)
```

```{r}
#load in data from the excel that I have recorded
data <- read_excel("database.xlsx")
WriteXLS(data, ExcelFileName = "database.xlsx")
```

```{r}
#convert the date formatting, from char to date
data$`Issue date`= as.Date(data$`Issue date`)
data$`Maturity date` = as.Date(data$`Maturity date`)
#change the coupon rate to per 100 dollars instead of percentage
data$`Coupon rate` = (data$`Coupon rate`)*100
```

```{r}
#generate new variables from the start date to end date, which has total 10 days
data <- data %>% 
  mutate(date_1 = as.Date('2022/1/10',format='%Y/%m/%d')) %>%
  mutate(date_2 = as.Date('2022/1/11',format='%Y/%m/%d')) %>%
  mutate(date_3 = as.Date('2022/1/12',format='%Y/%m/%d')) %>%
  mutate(date_4 = as.Date('2022/1/13',format='%Y/%m/%d')) %>%
  mutate(date_5 = as.Date('2022/1/14',format='%Y/%m/%d')) %>%
  mutate(date_6 = as.Date('2022/1/17',format='%Y/%m/%d')) %>%
  mutate(date_7 = as.Date('2022/1/18',format='%Y/%m/%d')) %>%
  mutate(date_8 = as.Date('2022/1/19',format='%Y/%m/%d')) %>%
  mutate(date_9 = as.Date('2022/1/20',format='%Y/%m/%d')) %>%
  mutate(date_10 = as.Date('2022/1/21',format='%Y/%m/%d'))
```

```{r}
#generate time to maturity according to observation date
data$date_1_dtd <- as.numeric((data$`Maturity date`- data$date_1), units="days")/360
data$date_2_dtd <- as.numeric((data$`Maturity date`- data$date_2), units="days")/360
data$date_3_dtd <- as.numeric((data$`Maturity date`- data$date_3), units="days")/360
data$date_4_dtd <- as.numeric((data$`Maturity date`- data$date_4), units="days")/360
data$date_5_dtd <- as.numeric((data$`Maturity date`- data$date_5), units="days")/360
data$date_6_dtd <- as.numeric((data$`Maturity date`- data$date_6), units="days")/360
data$date_7_dtd <- as.numeric((data$`Maturity date`- data$date_7), units="days")/360
data$date_8_dtd <- as.numeric((data$`Maturity date`- data$date_8), units="days")/360
data$date_9_dtd <- as.numeric((data$`Maturity date`- data$date_9), units="days")/360
data$date_10_dtd <- as.numeric((data$`Maturity date`- data$date_10), units="days")/360
```


## Question 4:

```{r}
#define function  by Newton's method
nw_function <- function (f, f1, x_0 = 0, num = 100, eps = 1e-05, eps1 = 1e-05) 
{   x_1 = x_0
    x_2 = x_1 - f(x_1)/f1(x_1)
    i = 0
    while ((abs(x_2 - x_1) > eps) & (i < num)) {
        x_1= x_2
        x_2 = x_1 - f(x_1)/f1(x_1)
        i = i + 1}
    if (abs(f(x_2)) < eps1) {
        return(x_1)}
    else print("fail")
}
```



```{r}
#add a date order
date_order <- data.frame(data$date_1[1], data$date_2[1], data$date_3[1], data$date_4[1], data$date_5[1], data$date_6[1], data$date_7[1], data$date_8[1], data$date_9[1], data$date_10[1])
#calculate the ytm for each bond on each day and define these new variables first
rep(0, 10) -> ytm_bond_1 -> ytm_bond_2 -> ytm_bond_3 -> ytm_bond_4 -> ytm_bond_5 -> ytm_bond_6 -> ytm_bond_7 -> ytm_bond_8 -> ytm_bond_9 -> ytm_bond_10 -> ytm_bond_11
#do the same thing for yield curve
rep(0, 10) -> yield_1 -> yield_2 -> yield_3 -> yield_4 -> yield_5 -> yield_6 -> yield_7 -> yield_8 -> yield_9 -> yield_10 -> yield_11

```

```{r}
#calculate for bond_1
for (i in 1:10){#iteration over 10 days of observation
  #find yield for each bond 
  b=1; c = data[b,4]/2
  #ytm
  ai_1 = ((as.numeric(date_order[1,i] - data$`Maturity date`[b]) + 180*b)/360) * (2*c)
  ytm_bond_1[i]= as.numeric(-ln(((data[b,5+i]+ai_1))/(N+c))/(data[b,25+i]))
  #spot rate
  yield_1[i] = as.numeric(-ln((data[b,5+i]+ai_1)/(N+c))/(data[b,25+i]))
}
```

```{r}
#calculate for bond_2
for (i in 1:10){
  b=2;c=data[b,4]/2
  ai_2 = ((as.numeric(date_order[1,i] - data$`Maturity date`[b]) + 180*b)/360) * (2*c)
  #time for each coupon and principle payment
  for (j in 1:2){assign(paste("t2", j, sep="_"), data[b,25+i]-(2-j)*0.5)} 
  #ytm
  f <- nw_function(function(x) (-1)*(data[b,5+i]+ai_2)+c*exp(-t2_1*x)+(100+c)*exp(-t2_2*x),
          function(x) c*exp(-t2_1*x)*(-t2_1)+(100+c)*exp(-t2_2*x)*(-t2_2), x_0 = 0)
  ytm_bond_2[i]= as.numeric(f)
  #spot rate
  yield_2[i] = as.numeric((-ln(((data[b,5+i])+ ai_2 -c*exp(-t2_1*yield_1[i]))/(100+c)))/t2_2)
}
```

```{r}
#calculate for bond_3
for (i in 1:10){
  b=3;c=data[b,4]/2
  ai_3 = ((as.numeric(date_order[1,i] - data$`Maturity date`[b]) + 180*b)/360) * (2*c)
  for (j in 1:3){assign(paste("t3", j, sep="_"), data[b,25+i]-(3-j)*0.5)}  
  #ytm
  f <- nw_function(function(x) (-1)*(data[b,5+i]+ai_3)+c*exp(-t3_1*x)+c*exp(-t3_2*x)+(100+c)*exp(-t3_3*x),
          function(x) (c*exp(-t3_1*x)*(-t3_1)+c*exp(-t3_2*x)*(-t3_2)
                      +(100+c)*exp(-t3_3*x)*(-t3_3)), x_0 = 0)
  ytm_bond_3[i]= as.numeric(f)
  #spot rate
  yield_3[i] = as.numeric((-ln(((data[b,5+i]+ai_3)-c*exp(-t3_1*yield_1[i])-c*exp(-t3_2*yield_2[i]))
                       /(100+c)))/t3_3)
}
```

```{r}
#calculate for bond_4
for (i in 1:10){
  b=4;c=data[b,4]/2
  ai_4 = ((as.numeric(date_order[1,i] - data$`Maturity date`[b]) + 180*b)/360) * (2*c)
  for (j in 1:4){assign(paste("t4", j, sep="_"), data[b,25+i]-(4-j)*0.5)}
  #ytm
  f <- nw_function(function(x) ((-1)*(data[b,5+i]+ai_4)+c*exp(-t4_1*x)+c*exp(-t4_2*x)
                       +c*exp(-t4_3*x)+(100+c)*exp(-t4_4*x)),
          function(x) (c*exp(-t4_1*x)*(-t4_1)+c*exp(-t4_2*x)*(-t4_2)+ 
                       c*exp(-t4_3*x)*(-t4_3)+(100+c)*exp(-t4_4*x)*(-t4_4)), x_0 = 0)
  ytm_bond_4[i] = as.numeric(f)
  #spot rate
  yield_4[i] = as.numeric((-ln(((data[b,5+i]+ai_4)-c*exp(-t4_1*yield_1[i])
                     -c*exp(-t4_2*yield_2[i])
                     -c*exp(-t4_3*yield_3[i]))/(100+c)))/t4_4)
}
```


```{r}
#calculate for bond_5
for (i in 1:10){
  b=5;c=data[b,4]/2
  ai_5 = ((as.numeric(date_order[1,i] - data$`Maturity date`[b]) + 180*b)/360) * (2*c)
  for (j in 1:5){assign(paste("t5", j, sep="_"), data[b,25+i]-(5-j)*0.5)}
  #ytm
  f <- nw_function(function(x) ((-1)*(data[b,5+i]+ai_5)+c*exp(-t5_1*x)+c*exp(-t5_2*x)
                       +c*exp(-t5_3*x)+c*exp(-t5_4*x)+(100+c)*exp(-t5_5*x)),
          function(x) (c*exp(-t5_1*x)*(-t5_1)+c*exp(-t5_2*x)*(-t5_2)+ 
                       c*exp(-t5_3*x)*(-t5_3)+c*exp(-t5_4*x)*(-t5_4)+
                         (100+c)*exp(-t5_5*x)*(-t5_5)), x_0 = 0)
  ytm_bond_5[i]= as.numeric(f)
}
```


```{r}  
#linear prediction for spot rate where have missing values
for (i in 1:10){
  x<- c(0, t4_1, t4_2, t4_3, t4_4)
  y<- c(0, yield_1[i], yield_2[i], yield_3[i], yield_4[i])
  r_1 = approx(x,y, xout=t5_1)$y
  r_2 = approx(x,y, xout=t5_2)$y
  r_3 = approx(x,y, xout=t5_3)$y
  r_4 = approx(x,y, xout=t5_4)$y
  #spot rate
  yield_5[i] = as.numeric((-ln(((data[b,5+i]+ai_5)-c*exp(-t5_1*r_1)
                        -c*exp(-t5_2*r_2)
                        -c*exp(-t5_3*r_3)
                        -c*exp(-t5_3*r_4))/
                         (100+c)))/t5_5)
}
```

```{r}
#calculate for bond_6
for (i in 1:10){
  b=6; c=data[b,4]/2
  ai_6 = ((as.numeric(date_order[1,i] - data$`Maturity date`[b]) + 180*b)/360) * (2*c)
  for (j in 1:6){assign(paste("t6", j, sep="_"), data[b,25+i]-(6-j)*0.5)} 
  #ytm
  f <- nw_function(function(x) (-1)*((data[b,5+i]+ai_6))+c*exp(-t6_1*x)+c*exp(-t6_2*x)
                       +c*exp(-t6_3*x)+c*exp(-t6_4*x)+c*exp(-t6_5*x)+(100+c)*exp(-t6_6*x),
          function(x) (c*exp(-t6_1*x)*(-t6_1)+c*exp(-t6_2*x)*(-t6_2)+ 
                       c*exp(-t6_3*x)*(-t6_3)+c*exp(-t6_4*x)*(-t6_4)+
                       c*exp(-t6_5*x)*(-t6_5)+(100+c)*exp(-t6_6*x)*(-t6_6)), x_0 = 0)
  ytm_bond_6[i] = as.numeric(f)
  #spot rate
  yield_6[i] = as.numeric((-ln(((data[b,5+i]+ai_6)-c*exp(-t6_1*r_1)
                        -c*exp(-t6_2*r_2)
                        -c*exp(-t6_3*r_3)
                        -c*exp(-t6_4*r_4)
                        -c*exp(-t6_5*yield_5[i]))/
                         (100+c)))/t6_6)
}
```

```{r}
#calculate for bond_7
for (i in 1:10){
  b=7; c=data[b,4]/2
  ai_7 = ((as.numeric(date_order[1,i] - data$`Maturity date`[b]) + 180*b)/360) * (2*c)
  for (j in 1:7){assign(paste("t7", j, sep="_"), data[b,25+i]-(7-j)*0.5)}
  #ytm
  f <- nw_function(function(x) ((-1)*((data[b,5+i]+ai_7))+c*exp(-t7_1*x)+c*exp(-t7_2*x)
                       +c*exp(-t7_3*x)+c*exp(-t7_4*x)+c*exp(-t7_5*x)
                       +c*exp(-t7_6*x)+(100+c)*exp(-t7_7*x)),
          function(x) (c*exp(-t7_1*x)*(-t7_1)+c*exp(-t7_2*x)*(-t7_2)+ 
                       c*exp(-t7_3*x)*(-t7_3)+c*exp(-t7_4*x)*(-t7_4)+
                       c*exp(-t7_5*x)*(-t7_5)+c*exp(-t7_6*x)*(-t7_6)+
                       (100+c)*exp(-t7_7*x)*(-t7_7)), x_0 = 0)
  ytm_bond_7[i]= as.numeric(f)
  #spot rate
  yield_7[i] = as.numeric((-ln(((data[b,5+i]+ai_7)-c*exp(-t7_1*r_1)
                        -c*exp(-t7_2*r_2)
                        -c*exp(-t7_3*r_3)
                        -c*exp(-t7_4*r_4)
                        -c*exp(-t7_5*yield_5[i])
                        -c*exp(-t7_6*yield_6[i]))/
                         (100+c)))/t7_7)
}
```

```{r}
#calculate for bond_8
for (i in 1:10){
  b=8;c=data[b,4]/2
  ai_8 = ((as.numeric(date_order[1,i] - data$`Maturity date`[b]) + 180*b)/360) * (2*c)
  for (j in 1:8){assign(paste("t8", j, sep="_"), data[b,25+i]-(8-j)*0.5)}
  #ytm
  f <- nw_function(function(x) ((-1)*(data[b,5+i]+ai_8)+c*exp(-t8_1*x)+c*exp(-t8_2*x)
                       +c*exp(-t8_3*x)+c*exp(-t8_4*x)+c*exp(-t8_5*x)
                       +c*exp(-t8_6*x)+c*exp(-t8_7*x)+(100+c)*exp(-t8_8*x)),
          function(x) (c*exp(-t8_1*x)*(-t8_1)+c*exp(-t8_2*x)*(-t8_2)+ 
                       c*exp(-t8_3*x)*(-t8_3)+c*exp(-t8_4*x)*(-t8_4)+
                       c*exp(-t8_5*x)*(-t8_5)+c*exp(-t8_6*x)*(-t8_6)+
                       c*exp(-t8_7*x)*(-t8_7)+(100+c)*exp(-t8_8*x)*(-t8_8)), x_0 = 0)
  ytm_bond_8[i]= as.numeric(f)
  #spot rate
  yield_8[i] = as.numeric((-ln(((data[b,5+i]+ai_8)-c*exp(-t8_1*r_1)
                        -c*exp(-t8_2*r_2)
                        -c*exp(-t8_3*r_3)
                        -c*exp(-t8_4*r_4)
                        -c*exp(-t8_5*yield_5[i])
                        -c*exp(-t8_6*yield_6[i])
                        -c*exp(-t8_7*yield_7[i]))/
                         (100+c)))/t8_8)
}
```

```{r}
#calculate for bond_9
for (i in 1:10){
  b=9;c=data[b,4]/2
  ai_9 = ((as.numeric(date_order[1,i] - data$`Maturity date`[b]) + 180*b)/360) * (2*c)
  for (j in 1:9){assign(paste("t9", j, sep="_"), data[b,25+i]-(9-j)*0.5)}
  #ytm
  f <- nw_function(function(x) ((-1)*(data[b,5+i]+ai_9)+c*exp(-t9_1*x)+c*exp(-t9_2*x)
                       +c*exp(-t9_3*x)+c*exp(-t9_4*x)+c*exp(-t9_5*x)
                       +c*exp(-t9_6*x)+c*exp(-t9_7*x)+c*exp(-t9_8*x)+
                       (100+c)*exp(-t9_9*x)),
          function(x) (c*exp(-t9_1*x)*(-t9_1)+c*exp(-t9_2*x)*(-t9_2)+ 
                       c*exp(-t9_3*x)*(-t9_3)+c*exp(-t9_4*x)*(-t9_4)+
                       c*exp(-t9_5*x)*(-t9_5)+c*exp(-t9_6*x)*(-t9_6)+
                       c*exp(-t9_7*x)*(-t9_7)+c*exp(-t9_8*x)*(-t9_8)+
                       (100+c)*exp(-t9_9*x)*(-t9_9)), x_0 = 0)
  ytm_bond_9[i]= as.numeric(f)
  #spot rate
  yield_9[i] = as.numeric((-ln(((data[b,5+i]+ai_9)-c*exp(-t9_1*r_1)
                        -c*exp(-t9_2*r_2)
                        -c*exp(-t9_3*r_3)
                        -c*exp(-t9_4*r_4)
                        -c*exp(-t9_5*yield_5[i])
                        -c*exp(-t9_6*yield_6[i])
                        -c*exp(-t9_7*yield_7[i])
                        -c*exp(-t9_8*yield_8[i]))/
                         (100+c)))/t9_9)
}
```


```{r}
#calculate for bond_10
for (i in 1:10){
  b=10;c=data[b,4]/2
  ai_10 = ((as.numeric(date_order[1,i] - data$`Maturity date`[b]) + 180*b)/360) * (2*c)
  for (j in 1:10){assign(paste("t10", j, sep="_"), data[b,25+i]-(10-j)*0.5)}
  #ytm
  f <- nw_function(function(x) ((-1)*(data[b,5+i]+ai_10)+c*exp(-t10_1*x)+c*exp(-t10_2*x)
                       +c*exp(-t10_3*x)+c*exp(-t10_4*x)+c*exp(-t10_5*x)
                       +c*exp(-t10_6*x)+c*exp(-t10_7*x)+c*exp(-t10_8*x)
                       +c*exp(-t10_9*x)+(100+c)*exp(-t10_10*x)),
          function(x) (c*exp(-t10_1*x)*(-t10_1)+c*exp(-t10_2*x)*(-t10_2)+ 
                       c*exp(-t10_3*x)*(-t10_3)+c*exp(-t10_4*x)*(-t10_4)+
                       c*exp(-t10_5*x)*(-t10_5)+c*exp(-t10_6*x)*(-t10_6)+
                       c*exp(-t10_7*x)*(-t10_7)+c*exp(-t10_8*x)*(-t10_8)+
                       c*exp(-t10_9*x)*(-t10_9)+(100+c)*exp(-t10_10*x)*(-t10_10)), x_0 = 0)
  ytm_bond_10[i]= as.numeric(f)
  #spot rate
  yield_10[i] = as.numeric((-ln(((data[b,5+i]+ai_10)-c*exp(-t10_1*r_1)
                        -c*exp(-t10_2*r_2)
                        -c*exp(-t10_3*r_3)
                        -c*exp(-t10_4*r_4)
                        -c*exp(-t10_5*yield_5[i])
                        -c*exp(-t10_6*yield_6[i])
                        -c*exp(-t10_7*yield_7[i])
                        -c*exp(-t10_8*yield_8[i])
                        -c*exp(-t10_9*yield_9[i]))/
                         (100+c)))/t10_10)
}
```

```{r}
#calculate for bond_11
for (i in 1:10){
  b=11;c=data[b,4]/2
  ai_11 = ((as.numeric(date_order[1,i] - data$`Maturity date`[b]) + 180*b)/360) * (2*c)
  for (j in 1:11){assign(paste("t11", j, sep="_"), data[b,25+i]-(11-j)*0.5)}
  #ytm
  f <- nw_function(function(x) ((-1)*(data[b,5+i]+ai_11)+c*exp(-t11_1*x)+c*exp(-t11_2*x)
                       +c*exp(-t11_3*x)+c*exp(-t11_4*x)+c*exp(-t11_5*x)
                       +c*exp(-t11_6*x)+c*exp(-t11_7*x)+c*exp(-t11_8*x)
                       +c*exp(-t11_9*x)+c*exp(-t11_10*x)+(100+c)*exp(-t11_11*x)),
          function(x) (c*exp(-t11_1*x)*(-t11_1)+c*exp(-t11_2*x)*(-t11_2)+ 
                       c*exp(-t11_3*x)*(-t11_3)+c*exp(-t11_4*x)*(-t11_4)+
                       c*exp(-t11_5*x)*(-t11_5)+c*exp(-t11_6*x)*(-t11_6)+
                       c*exp(-t11_7*x)*(-t11_7)+c*exp(-t11_8*x)*(-t11_8)+
                       c*exp(-t11_9*x)*(-t11_9)+c*exp(-t11_10*x)*(-t11_10)+
                       (100+c)*exp(-t11_11*x)*(-t11_11)), x_0 = 0)
  ytm_bond_11[i]= as.numeric(f)
  #spot rate
  yield_11[i] = as.numeric((-ln(((data[b,5+i]+ai_11)-c*exp(-t11_1*r_1)
                        -c*exp(-t11_2*r_2)
                        -c*exp(-t11_3*r_3)
                        -c*exp(-t11_4*r_4)
                        -c*exp(-t11_5*yield_5[i])
                        -c*exp(-t11_6*yield_6[i])
                        -c*exp(-t11_7*yield_7[i])
                        -c*exp(-t11_8*yield_8[i])
                        -c*exp(-t11_9*yield_9[i])
                        -c*exp(-t11_10*yield_10[i]))/
                         (100+c)))/t11_11)
}
```

### Part a: Yield to Maturity Curve
```{r }
#plot ytm curve
ytm_table <-cbind(ytm_bond_1, ytm_bond_2, ytm_bond_3, ytm_bond_4,
                   ytm_bond_5, ytm_bond_6, ytm_bond_7, ytm_bond_8, 
                   ytm_bond_9, ytm_bond_10, ytm_bond_11)
for (i in 1:10){assign(paste("ytm_day", i, sep="_"), ytm_table[i,])}
ytm_day_table <-data.frame(bond_order =c(1:11), ytm_day_1, ytm_day_2, ytm_day_3, ytm_day_4, ytm_day_5, ytm_day_6, ytm_day_7, ytm_day_8, ytm_day_8, ytm_day_10)
maturity_time <- data$`Maturity date`
plot(x=maturity_time, y= ytm_day_1, type = "l", ylim = c(0.002,0.02), col = c(1),
     main = "Yield-to-Maturity Curve ",
     xlab = "Maturity Date", ylab="YTM")
lines(x=maturity_time, y= ytm_day_2, col = c(2))
lines(x=maturity_time, y= ytm_day_3, col = c(3))
lines(x=maturity_time, y= ytm_day_4, col = c(4))
lines(x=maturity_time, y= ytm_day_5, col = c(5))
lines(x=maturity_time, y= ytm_day_6, col = c(6))
lines(x=maturity_time, y= ytm_day_7, col = c(7))
lines(x=maturity_time, y= ytm_day_8, col = c(8))
lines(x=maturity_time, y= ytm_day_9, col = c(9))
lines(x=maturity_time, y= ytm_day_10, col = c(10))
legend("bottomright", legend =c("01-10-2022", "01-11-2022", "01-12-2022", "01-13-2022", "01-14-2022", "01-17-2022", "01-18-2022", "01-19-2022", "01-20-2022","01-21-2022"), col=c(1:10), lty = 1:1, cex =0.5)
```


### Part b: Spot Curve
```{r }
#plot spot curve
spot_table <-data.frame(yield_1, yield_2, yield_3, yield_4, yield_5, 
            yield_6, yield_7, yield_8, yield_9, yield_10,yield_11)
for (i in 1:10){
  assign(paste("spot_day", i, sep="_"), spot_table[i,])
}
plot(x=data$date_1_dtd, y= spot_day_1, type = "l", ylim = c(0.002,0.02), col = c(1), 
     main = "Spot Curve ",
     xlab = "Time to Maturity", ylab="Spot Rate")
lines(x=data$date_2_dtd, y= spot_day_2, col = c(2))
lines(x=data$date_3_dtd, y= spot_day_3, col = c(3))
lines(x=data$date_4_dtd, y= spot_day_4, col = c(4))
lines(x=data$date_5_dtd, y= spot_day_5, col = c(5))
lines(x=data$date_6_dtd, y= spot_day_6, col = c(6))
lines(x=data$date_7_dtd, y= spot_day_7, col = c(7))
lines(x=data$date_8_dtd, y= spot_day_8, col = c(8))
lines(x=data$date_9_dtd, y= spot_day_9, col = c(9))
lines(x=data$date_10_dtd, y= spot_day_10, col = c(10))
legend("bottomright", legend =c("01-10-2022", "01-11-2022", "01-12-2022", "01-13-2022", "01-14-2022", "01-17-2022", "01-18-2022", "01-19-2022", "01-20-2022","01-21-2022"), col=c(1:10), lty = 1:1, cex =0.5)
```

```{r }
#generate empty list for each date forward rate of size 4:
# 1yr-1yr, 1yr-2yr, 1yr-3yr, 1yr-4yr
# we need to do it for all 10 days
for (j in 1:10){assign(paste("forward", j, sep="_"), rep(NA, 4))}
R<- matrix(NA, nrow = 10, ncol = 5)
for (j in 1:5){
    x<- c(as.list(data$date_1_dtd))
    y<- c(as.list(spot_day_1))
    R[1,j] = approx(x,y, xout=j)$y
}
for (j in 1:5){
    x<- c(as.list(data$date_2_dtd))
    y<- c(as.list(spot_day_2))
    R[2,j] = approx(x,y, xout=j)$y
}
for (j in 1:5){
    x<- c(as.list(data$date_3_dtd))
    y<- c(as.list(spot_day_3))
    R[3,j] = approx(x,y, xout=j)$y
}
for (j in 1:5){
    x<- c(as.list(data$date_4_dtd))
    y<- c(as.list(spot_day_4))
    R[4,j] = approx(x,y, xout=j)$y
}
for (j in 1:5){
    x<- c(as.list(data$date_5_dtd))
    y<- c(as.list(spot_day_5))
    R[5,j] = approx(x,y, xout=j)$y
}
for (j in 1:5){
    x<- c(as.list(data$date_6_dtd))
    y<- c(as.list(spot_day_6))
    R[6,j] = approx(x,y, xout=j)$y
}
for (j in 1:5){
    x<- c(as.list(data$date_7_dtd))
    y<- c(as.list(spot_day_7))
    R[7,j] = approx(x,y, xout=j)$y
}
for (j in 1:5){
    x<- c(as.list(data$date_8_dtd))
    y<- c(as.list(spot_day_8))
    R[8,j] = approx(x,y, xout=j)$y
}
for (j in 1:5){
    x<- c(as.list(data$date_9_dtd))
    y<- c(as.list(spot_day_9))
    R[9,j] = approx(x,y, xout=j)$y
}
for (j in 1:5){
    x<- c(as.list(data$date_10_dtd))
    y<- c(as.list(spot_day_10))
    R[10,j] = approx(x,y, xout=j)$y
}
Forward <- matrix(NA, nrow = 10, ncol = 4)
for (i in 1:10){
  for (j in 1:4){
    Forward[i,j] = (R[i,j+1]*(j+1) - R[i,j]*j)
  }}
plot(x=c(1:4), y= Forward[1,], type = "l", ylim = c(0.002,0.03), col = c(1), 
     main = "Forward Rate Curve",
     xlab = "Year difference", ylab="Forward Rate")
lines(x=c(1:4), y= Forward[2,], col = c(2))
lines(x=c(1:4), y= Forward[3,], col = c(3))
lines(x=c(1:4), y= Forward[4,], col = c(4))
lines(x=c(1:4), y= Forward[5,], col = c(5))
lines(x=c(1:4), y= Forward[6,], col = c(6))
lines(x=c(1:4), y= Forward[7,], col = c(7))
lines(x=c(1:4), y= Forward[8,], col = c(8))
lines(x=c(1:4), y= Forward[9,], col = c(9))
lines(x=c(1:4), y= Forward[10,], col = c(10))
legend("bottomright", legend =c("01-10-2022", "01-11-2022", "01-12-2022", "01-13-2022", "01-14-2022", "01-17-2022", "01-18-2022", "01-19-2022", "01-20-2022","01-21-2022"), col=c(1:10), lty = 1:1, cex =0.5)
```


## Question 5:
```{r}
#find the covariance matrix for the log-returns of yield
rep(0, 9) -> X_1 -> X_2 -> X_3 -> X_4 -> X_5
rep(0, 10) -> r_1 -> r_2 -> r_3 -> r_4 -> r_5
maturity_time <- as.numeric(data$`Maturity date` - data$date_1)/365
for (i in 1:10){
  slope_1 = (ytm_table[i,3] - ytm_table[i,2])/(maturity_time[3] - maturity_time[2])
  r_1[i]= slope_1*1 + ytm_table[i,2]- slope_1*maturity_time[2]
  slope_2 = (ytm_table[i,5] - ytm_table[i,4])/(maturity_time[5] - maturity_time[4])
  r_2[i]= slope_2*2 + ytm_table[j,4]- slope_2*maturity_time[4]
  slope_3 = (ytm_table[i,7] - ytm_table[i,6])/(maturity_time[7] - maturity_time[6])
  r_3[i]= slope_3*3 + ytm_table[j,6]- slope_3*maturity_time[6]
  slope_4 = (ytm_table[i,9] - ytm_table[i,8])/(maturity_time[9] - maturity_time[8])
  r_4[i]=slope_4*4 + ytm_table[j,8]- slope_4*maturity_time[8]
  slope_5 = (ytm_table[i,11] - ytm_table[i,10])/(maturity_time[11] - maturity_time[10])
  r_5[i]=slope_5*5 + ytm_table[i,10]- slope_5*maturity_time[10]
}
for (i in 1:9){
  X_1[i]= log(r_1[i+1]/r_1[i])
  X_2[i]= log(r_2[i+1]/r_2[i])
  X_3[i]= log(r_3[i+1]/r_3[i])
  X_4[i]= log(r_4[i+1]/r_4[i])
  X_5[i]= log(r_5[i+1]/r_5[i])
}
X = cbind(X_1, X_2, X_3, X_4, X_5)
cov_X = cov(X)
cov_X
```

```{r}
#find the covariance matrix 
cov_F = cov(Forward)
cov_F
```

### Part b: Eigenvalue and Eigenvector of Covariance Matrix
```{r}
#eigenvalue and eigenvector of Covariance Matrix for log yield
eigen(cov_X)
(transpose <- t(eigen(cov_X)$vectors))
#eigenvalue and eigenvector of Covariance Matrix for log forward rate
eigen(cov_F)
(transpose <- t(eigen(cov_F)$vectors))
```